### ISSUE TITLE
.saf file not found

### ISSUE THREAD

**Issue by dionysisskouras** [MadAnalysis/madanalysis5#115] opened 2022-07-25 16:05 UTC
Hello people of MA5
 I am trying to run an analysis that contains 2,000,000 events but in the end of the compilation I get 
"File called dataset.saf not found"
I guess it is the large number of events but I've done it in the past
Thank you
Dionysis

**Comment by jackaraz** [comment] 2022-07-25 16:10
Hi @dionysisskouras, we will need a bit more information. We can not help if you just tell us, "I did this, but it failed".

**Comment by dionysisskouras** [comment] 2022-07-25 16:22
This is the final message I get
![image](https://user-images.githubusercontent.com/105206413/180826628-e6cb1511-fd0d-4775-b84f-5a994aeea338.png)
This internal error hasn't stopped me from getting results in the past with smaller number of events.
When I surpass 1,000,000 events it stops working . 
Also the sm dataset that appears in the message is a combination of two .lhe files (1,000,000 events each)

**Comment by dionysisskouras** [comment] 2022-07-25 16:23
Previously I got a normal result as expected but now I just changed a command for normalization

**Comment by jackaraz** [comment] 2022-07-25 16:26
Again this is not enough. We need to know how are you running MadAnalysis, which version are you using, are you running in normal or expert mode, and which third-party software are you using? Additionally, I can see that your sample file is problematic; we can not guarantee you will get the correct result with such a file.

**Comment by dionysisskouras** [comment] 2022-07-25 16:30
My MA5 release is 1.9.6 and the .lhe file is output from pythia8. I am running in normal mode. Finally, I would be interested at least getting a result at this stage.

**Comment by dionysisskouras** [comment] 2022-07-25 16:47
I understand that and I am planning to fix the file but the strange thing is that I have used the exact same commands just with a different normalization method and it worked, with that internal warning too.

**Comment by jackaraz** [comment] 2022-07-25 16:50
We can check it out if you submit a [bug report](https://github.com/MadAnalysis/madanalysis5/issues/new?assignees=&labels=bug&template=bug_report.yml) with 10 events attached and all the commands that you used to reproduce the error.

**Comment by dionysisskouras** [comment] 2022-07-25 18:07
Is this of any help? 
Note : it is still the 2million event sample 
![image_2022-07-25_210721740](https://user-images.githubusercontent.com/105206413/180844782-50a8b01b-407a-4a36-92a1-22e87bd8b826.png)

**Comment by dionysisskouras** [comment] 2022-07-25 18:08
Again ,the strange thing is that it works with a smaller sample

**Comment by jackaraz** [comment] 2022-07-26 11:22
Hi @dionysisskouras, sorry I do not have the ability to read your mind yet, so there is no way I can know what you are doing to get this error since we haven't got any such reports before. The only advice I can give, with the limited information provided, is to use smaller samples and combine them if it works. I'm closing this issue; please don't hesitate to reopen it when you are ready to provide detailed information to reproduce your error. Please don't hesitate to follow the proper procedure that we laid in our [bug report](https://github.com/MadAnalysis/madanalysis5/issues/new?assignees=&labels=bug&template=bug_report.yml) section.

PS: maybe your ram is not large enough to handle such a large number of events.

**Closed by jackaraz** 2022-07-26 11:22 UTC
Labels: invalid

**Comment by dionysisskouras** [comment] 2022-10-11 08:09
I understand that and I am planning to fix the file but the strange thing
is that I have used the exact same commands just with a different
normalization method and it worked, with that internal warning too.

Στις Δευ, 25 Ιουλ 2022, 19:33 ο χρήστης Jack Y. Araz <
***@***.***> έγραψε:

**Comment by jackaraz** [comment] 2022-10-11 08:13
Hi @dionysisskouras, "it worked" doesn't mean that it worked as it was supposed to. You should be vigilant; although we are trying our best to implement warnings and errors for possible issues that may occur, we can not know everything in advance.
