### ISSUE TITLE
Sorting number of jets with maximum events at invariant mass using madanalysis5

### ISSUE THREAD

**Issue by umar0341** [MadAnalysis/madanalysis5#117] opened 2022-08-01 13:37 UTC
### Question

Hi, I have a large number of jets up to 12 jets. I want to get those combinations that form Higgs jets but I don't want to draw each pair separately one by one. kindly tell me another way so that I can get my required combination at my defined invariant Higgs mass instead of plotting all combinations and comparing them. my process is as follows

mu+ mu- ------> HH , H ----> tt~ , t ----> w+b , t~ ----> w-b~ w+- ------> j j

example commands
plot M(j[1] j[2]) 100 0 3000 [logY]
plot M(j[1] j[3]) 100 0 3000 [logY]
plot M(j[1] j[4]) 100 0 3000 [logY]
plot M(j[2] j[3]) 100 0 3000 [logY]
plot M(j[2] j[4]) 100 0 3000 [logY]
plot M(j[3] j[4]) 100 0 3000 [logY]

**Comment by jackaraz** [comment] 2022-08-01 13:42
duplicate of #116

**Closed by jackaraz** 2022-08-01 13:42 UTC
Labels: duplicate
