### ISSUE TITLE
Observables when more than 2 jets in final state

### ISSUE THREAD

**Issue by pramod-pixel** [MadAnalysis/madanalysis5#15] opened 2022-01-20 10:32 UTC
### Question

Hi,
I have a process with 2 jets in the final state. I found that Ma5 results for observables corresponding to these 2 jets do not match with ExRoot and Ma4. I'm wondering where the problem is created by me.
Command for PT observables (for example) is written as,
plot PT(j[1]) 30 0 500
plot PT(j[2]) 30 0 500
Thanks

**Comment by jackaraz** [comment] 2022-01-20 10:39
Hi @pramod-pixel, `madanalysis4` has been outdated since 2004 and haven't been updated ever since. Its results are not reliable. But please do let us know if you find an inconsistency in `madanalysis5`.

**Comment by pramod-pixel** [comment] 2022-01-20 11:04
To figure out any consistency, I cross-checked with ExRootAnalysis. I found that the results are different in both cases.

**Comment by jackaraz** [comment] 2022-01-20 11:09
> To figure out any consistency, I cross-checked with ExRootAnalysis. I found that the results are different in both cases.

Could you please elaborate on it? I have no idea what and how you got your results or which version of `madanalysis` and FastJet you are using. Without this information, I can not help you. Also, I can not say anything about `ExRootAnalysis` since I'm not the developer. So it would be better if you compare the tools within themselves or by directly using FastJet independently.

**Comment by pramod-pixel** [comment] 2022-01-20 11:38
Versions that I'm using are,
MA5 release: 1.8.58, FastJet: 3.3.3. 
As I mentioned in the main question, all distributions corresponding to particles except jets are consistent. Is there any issue with the identification of tew jets?

**Comment by jackaraz** [comment] 2022-01-20 11:47
No there hasn't been any report on jet distributions being inconsistent. If you like to submit a bug report please submit a **detailed** report from [here](https://github.com/MadAnalysis/madanalysis5/issues/new?assignees=&labels=bug&template=bug_report.yml) so that we can reproduce your results and investigate further. Note that if you like to submit a bug report on this, I would suggest submitting an **independent** confirmation of the distributions using FastJet only with your code. We **cannot** solve your problem based on `ExRootAnalysis` or `madanalysis4`.

**Comment by pramod-pixel** [comment] 2022-01-20 14:47
I don't know FastJet is used for computation or not. If it is not used then how to enable it? I have installed FastJet as you can see below,
MA5: Checking optional packages devoted to data processing:
MA5:      - Zlib                     [OK]
MA5:      - FastJet                  [OK]
MA5:      - Root                     [OK]


Commands given for computation are, 
import eventj.lhe.gz
plot ETA(j[1]) 30 -6.0 6.0
plot ETA(j[2]) 30 -6.0 6.0
plot PT(j[1]) 30 0 500
plot PT(j[2]) 30 0 500
submit ./output

**Comment by jackaraz** [comment] 2022-01-20 14:55
Hi @pramod-pixel, you are not even reconstructing jets and your sample is a parton sample. That's why I've been asking for **detailed** information from you so that I know what you are trying to do which is still not completely clear. LHE files contain matrix-element level information which does not require jet reconstruction since the sample does not include parton shower but quarks only. I suggest reading our [documentation](http://arxiv.org/abs/1206.1599) and [tutorials](https://madanalysis.irmp.ucl.ac.be/wiki/tutorials) before dealing with the software. In those links, you can find all the information you need to use MadAnalysis 5.

**Comment by pramod-pixel** [comment] 2022-01-20 16:15
I have generated a process at the Parton level that has two light quarks (u u~ d d~ s s~ c c~ g) in the final state. I want to plot distributions for these two quarks. Is it possible to do in Ma5? Still, I don't see it in the manual, sorry.

**Comment by jackaraz** [comment] 2022-01-20 16:19
Hi please read the documentation written in section 3 its also shown in tutorials. I'm closing this issue since this is not an issue but a lack of reading the supporting material.

**Closed by jackaraz** 2022-01-20 16:19 UTC
Labels: invalid
